language: node_js
#sudo: required
node_js:
    - "6"

dist: trusty

script:
    - npm install
    - npm run lint
    - npm test
    - rm -rf node_modules/
    - nvm use 0.10
    - npm install
    - npm test
